version: '2'
services:
  default:
    build:
      context: .
    cap_add:
      - SYS_ADMIN
    ports:
      - "5900:5900"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
  mariadb:
    image: mariadb:10.4.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  mysql-5.5:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  mysql-5.6:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  mysql-5.7:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  postgresql-10:
    image: postgres:10.6
    restart: always
    environment:
      POSTGRES_PASSWORD: root
  postgresql-11:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_PASSWORD: root